server:
  port: @server.port@

spring:
  application:
    name: lianci

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: @lianci.datasource.jdbcUrl@
    username: @lianci.datasource.user@
    password: @lianci.datasource.password@

  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 30MB

  mvc:
    static-path-pattern: /image/**

doucument:
  uploadPath: /data/images
  imgPath: http://localhost:8081/springboot/images



mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: org.chnjkfp.lianci.dao.entity

#自定义参数
define:
  nginx:
    path: /Users/wuwei/